services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env

  db:
    image: mariadb:12-noble
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: